name: Main Workflow

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-compiler:
          - 4.12.x
          - 4.13.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Prepare opam
        run: |
          opam uninstall ppx_camlrack camlrack
          opam unpin ppx_camlrack camlrack

      - name: Pin packages
        run: |
          opam pin -yn add camlrack.dev .
          opam pin -yn add ppx_camlrack.dev .

      - name: Install camlrack dependencies
        run: opam install camlrack --deps-only --with-test --yes

      - name: Test camlrack
        run: |
          opam exec -- dune build -p camlrack --promote-install-files=false @install
          opam exec -- dune runtest -p camlrack

      - name: Install ppx_camlrack dependencies
        run: opam install ppx_camlrack --deps-only --with-test --yes

      - name: Test ppx_camlrack
        run: |
          opam exec -- dune build -p ppx_camlrack
          opam exec -- dune runtest -p ppx_camlrack
